version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: webshop-admin
    image: webshop-admin